### ISSUE TITLE
Update for README.md of getting started

### ISSUE THREAD

**Issue by woutslabbinck** [CommunitySolidServer/tutorials#1]
change `cd community-server` to `cd CommunitySolidServer`

**Comment by woutslabbinck** [comment]
Also at [componentjs](https://github.com/CommunitySolidServer/tutorials/blob/main/getting-started.md#customizing-imports) change the prefix `files-scs` to `css`

**Comment by joachimvh** [comment]
Done. Thanks for the reminder.
