### ISSUE TITLE
ERROR when following the tutorial: "Authentication client" section

### ISSUE THREAD

**Issue by skandarchahbouni** [CommunitySolidServer/tutorials#5]
I was following the Authentication and Client Applications tutorials in the repository:

git clone https://github.com/inrupt/solid-client-authn-js.git
cd solid-client-authn-js
npm ci

However, when I ran the "npm install" command, I encountered several errors and I'm not sure what is causing them. If anyone has encountered the same errors or knows how to resolve this issue, I would greatly appreciate your assistance.

here is the error:

npm ERR! code 1
npm ERR! path C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./bin/post-install
npm ERR! C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx\src\native\index.js:244
npm ERR!     throw loadError
npm ERR!     ^
npm ERR!
npm ERR! Error: Cannot find module '@nx/nx-win32-x64-msvc'
npm ERR! Require stack:
npm ERR! - C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx\src\native\index.js
npm ERR! - C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx\src\project-graph\utils\retrieve-workspace-files.js
npm ERR! - C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx\src\config\workspaces.js
npm ERR! - C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx\plugins\package-json-workspaces.js
npm ERR! - C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx\src\project-graph\utils\project-configuration-utils.js
npm ERR! - C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx\src\project-graph\build-nodes\workspace-projects.js
npm ERR! - C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx\src\project-graph\build-nodes\index.js
npm ERR! - C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx\src\project-graph\build-project-graph.js
npm ERR! - C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx\src\project-graph\project-graph.js
npm ERR! - C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx\bin\post-install.js
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:922:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1143:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
npm ERR!     at Object.<anonymous> (C:\Users\skand\Downloads\scs\solid-client-authn-js\node_modules\nx\src\native\index.js:66:29)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1256:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1119:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:960:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1143:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'C:\\Users\\skand\\Downloads\\scs\\solid-client-authn-js\\node_modules\\nx\\src\\native\\index.js',
npm ERR!     'C:\\Users\\skand\\Downloads\\scs\\solid-client-authn-js\\node_modules\\nx\\src\\project-graph\\utils\\retrieve-workspace-files.js',
npm ERR!     'C:\\Users\\skand\\Downloads\\scs\\solid-client-authn-js\\node_modules\\nx\\src\\config\\workspaces.js',
npm ERR!     'C:\\Users\\skand\\Downloads\\scs\\solid-client-authn-js\\node_modules\\nx\\plugins\\package-json-workspaces.js',
npm ERR!     'C:\\Users\\skand\\Downloads\\scs\\solid-client-authn-js\\node_modules\\nx\\src\\project-graph\\utils\\project-configuration-utils.js',
npm ERR!     'C:\\Users\\skand\\Downloads\\scs\\solid-client-authn-js\\node_modules\\nx\\src\\project-graph\\build-nodes\\workspace-projects.js',
npm ERR!     'C:\\Users\\skand\\Downloads\\scs\\solid-client-authn-js\\node_modules\\nx\\src\\project-graph\\build-nodes\\index.js',
npm ERR!     'C:\\Users\\skand\\Downloads\\scs\\solid-client-authn-js\\node_modules\\nx\\src\\project-graph\\build-project-graph.js',
npm ERR!     'C:\\Users\\skand\\Downloads\\scs\\solid-client-authn-js\\node_modules\\nx\\src\\project-graph\\project-graph.js',
npm ERR!     'C:\\Users\\skand\\Downloads\\scs\\solid-client-authn-js\\node_modules\\nx\\bin\\post-install.js'
npm ERR!   ]
npm ERR! }
npm ERR!
npm ERR! Node.js v18.16.1

npm ERR! A complete log of this run can be found in: C:\Users\skand\AppData\Local\npm-cache\_logs\2023-08-30T11_47_48_344Z-debug-0.log

**Comment by joachimvh** [comment]
I can confirm that I run into the same problem. Something must have changed in the latest version of that library.

Looking around, here was a potential solution: https://github.com/lerna/lerna/issues/3612#issuecomment-1495469808

Following all these steps:
 * Install the redist package
 * verify npm cache
 * Remove authn project and clone again

This still didn't fix the issue for me. What did eventually fix it was removing the `package-lock.json` in the project and then running `npm i` instead. I'm not sure if the steps before were also necessary. One of the install steps still fails but that one is not relevant for the tutorial.

I'll add some info about this to the tutorial and open an issue on the library about this.
